#!/bin/bash

# Директория для бэкапа
BACKUP_DIR="/tmp/backup"
# Исходная директория (домашняя)
SOURCE_DIR="$HOME/"
# Лог-файл
LOG_FILE="/var/log/backup_home.log"

# Проверяем, существует ли директория для бэкапа
mkdir -p "$BACKUP_DIR" || {
    logger -t "home-backup" "Ошибка: не удалось создать $BACKUP_DIR"
    exit 1
}

# Выполняем синхронизацию с rsync
rsync -avh --delete --checksum --exclude='.*/' "$SOURCE_DIR" "$BACKUP_DIR" &>> "$LOG_FILE"

# Проверяем код завершения rsync
if [ $? -eq 0 ]; then
    logger -t "home-backup" "Резервное копирование завершено успешно"
else
    logger -t "home-backup" "Ошибка резервного копирования (код $?)"
fi

sudo chmod +x /usr/local/bin/backup_home.sh
crontab -e
0 3 * * * /usr/local/bin/backup_home.sh

cat /var/log/backup_home.log

journalctl -t "home-backup"  # (systemd)
grep "home-backup" /var/log/syslog  # (syslog)
